name: demo_caller

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  call-workflow:
       uses: NewDemoOrg/new_repo/.github/workflows/blank.yml@main
  
    # steps:
    
    #  call-workflow:
    #    uses: NewDemoOrg/new_repo/.github/workflows/blank.yml@main
