name: export-and-branch-solution
# Export solution from DEV environment
#  unpack it and prepare, commit and push a git branch with the changes

on:
  
  push:
    branches: [ main ]




jobs:
  export-from-dev:
    runs-on: windows-latest
    

    steps:
    # - uses: actions/checkout@v2
    #   with:
    #     lfs: true
   
    - name: calling workflow
      uses: NewDemoOrg/new_repo/.github/workflows/blank.yml@main
