name: export-and-branch-solution

on:
  
  push:
    branches: [ main ]




jobs:
  export-from-dev:
    runs-on: windows-latest
    

    steps:
    
    - name: calling workflow
      uses: NewDemoOrg/new_repo/.github/workflows/blank.yml@main
